######################################################################
# Automatically generated by qmake (3.0) Wed Mar 28 13:16:04 2018
######################################################################

TEMPLATE = app
TARGET = btc-price-qt5
INCLUDEPATH += .

QT += widgets network
CONFIG += c++11

# Input
SOURCES += main.cpp \
exchangerate.cpp

HEADERS += exchangerate.h
